wandb:
  key: "40c5c10f4b03fb955b2343280005f183c6e39d70"
  project_name: "GSN_rain_prediction"

dataset:
  dir: "D:\\gsn_dataset\\2018"
  step: 3
  width: 64
  height: 64

dataLoader:
  batch_size: 10
  shuffle: True
  num_workers: 2

early_stopping:
  monitor: 'validation_loss'
  patience: 3
  verbose: False
  mode: 'min'

checkpoint:
  monitor: 'validation_loss'
  dirpath: './model/'
  filename: "model-{epoch:02d}-{validation_loss:.2f}"
  save_top_k: 3
  mode: 'min'

main_model:
  RNN_cell:
    _target_: src.architectures.ConvRNNCell
    input_channels: 1
    hidden_channels: 4
    kernel_size: 5
    depth: 1
    activation: torch.nn.ReLU
  loss_metrics:
    _target_: torchmetrics.MeanSquaredError
    squared: true    
  scheduler_step: 7
  scheduler_gamma: 0.9
  learning_rate: 0.01

trainer:
  accelerator: "gpu"
  devices: [0]
  max_epochs: 50
